services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

  # mongo:
  #   image: mongo:latest
  #   container_name: mongo_db
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: 123123
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - ./data/mongo:/data/db

volumes:
  postgres_data:
  redis_data:
  # mongo_data:
